repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.5
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff(linting)
      # Run the import sorter
      - id: ruff
        name: ruff(imports)
        args: [ --select, I, --fix]
      # Run the formatter.
      - id: ruff-format
        name: ruff(format)