#!/usr/bin/env sh

.venv/bin/uv pip compile --upgrade --generate-hashes --output-file requirements/prod.txt requirements/in/prod.in
.venv/bin/uv pip compile --upgrade --generate-hashes --output-file requirements/dev.txt requirements/in/dev.in
